theme: jekyll-theme-minimal
url: https://thomas-serre.com
title: Thomas Serre
description: "Machine and Biological Vision • Computational Neuroscience • AI&nbsp;•&nbsp;NeuroAI&nbsp;•&nbsp;XAI"
defaults:
  - scope:
      path: "assets/img"
    values:
      logo: logo.gif
# Force rebuild - updated 2025-11-15 15:35