theme: jekyll-theme-minimal
url: https://thomas-serre.com
title: Thomas Serre
description: "Computational neuroscience • AI • brain-inspired vision models • visual perception • explainable AI"
defaults:
  - scope:
      path: "assets/img"
    values:
      logo: logo.gif
# Force rebuild - updated $(date)